INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, '_edit_lock', '1549481465:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, 'feature-name', 'Massage');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, 'feature-header', 'OUR JET PHILOSOPHY');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, '_feature-header', 'field_558d8b87f901c');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, 'feature-body', '<h4>OUR JET PHILOSOPHY</h4>\n<p>We design spas based on how you will actually use them. The ComfortControl® system lets you customize the strength of massage. The SmartJet® system allows you to direct power to the jets you are using, instead of powering all the jets at once.</p>\n<p><strong>THE PERFECT MASSAGE</strong></p>\n<p>Highlife® Collection spas feature up to 7 different jets, offering different types of massage for various parts of the body:</p>\n<ul>\n<li>Every Highlife Collection spa features the Moto-Massage® DX jet that provides two powerful streams of water that sweep up and down the length of your back – there is nothing else like it</li>\n<li>Precision® jets work together in a powerful cluster to relieve tension in your back, neck and calves</li>\n<li>Directional Hydromassage jets provide targeted relief to problem areas with easy-to-adjust nozzles</li>\n</ul>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, 'image-slider', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, '_image-slider', 'field_558d8be2f901f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, 'feature-video', '<p><iframe src="https://www.youtube.com/embed/DihcVsLEKyc" width="100%" height="300" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, '_feature-video', 'field_558d8c12f9022');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (983, '_edit_lock', '1549481464:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (983, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (983, 'feature-name', 'Energy');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (983, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (983, 'feature-header', 'ENERGY EFFICIENCY');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (983, '_feature-header', 'field_558d8b87f901c');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (983, 'feature-body', '<h4>ENERGY EFFICIENCY</h4>\n<p>Highlife® Collection spas offer our very best in efficiency and energy saving design – which is why we call these models <em>Super Energy Efficient</em>. This is just one of the ways a Highlife Collection spa delivers the best value over time.</p>\n<p><strong>SAVING YOU MONEY</strong></p>\n<p>Highlife Collection models feature our complete Energy Smart® system. Every aspect of the spa has been optimized to create heat efficiently and maximize heat retention.</p>\n<ul>\n<li>Totally insulated with multiple layers of foam to lock in heat</li>\n<li>SilentFlo 5000® circulation pump that uses less energy than a 40 watt light bulb</li>\n<li>Custom-designed spa covers with an exclusive hinge seal to lock in heat</li>\n<li>Our No-Fault® heater that maximizes heat transfer and is covered by an unconditional 5-year warranty</li>\n<li>A pump shroud captures heat from the equipment compartment and transfers it to the water</li>\n<li>SmartJet® system lets you direct power only to the jet groups you want to use</li>\n</ul>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (983, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (983, 'image-slider', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (983, '_image-slider', 'field_558d8be2f901f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (983, 'feature-video', '<p><img src="https://csp-hot-spring-spas.s3.amazonaws.com/content-blocks/features/images/MPS-Highlife-Energy-Feature.jpg" alt="Vanguard Spa Cover" width="461" height="275" class="alignnone size-full wp-image-3310" /></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (983, '_feature-video', 'field_558d8c12f9022');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (991, '_edit_lock', '1549481609:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (991, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (991, 'feature-name', 'Water');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (991, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (991, 'feature-header', 'CLEANER SPA WATER');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (991, '_feature-header', 'field_558d8b87f901c');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (991, 'feature-body', '<h4>CLEANER SPA WATER</h4>\n<p>Crystal clear spa water is essential to your soaking experience, which is why we have invested in innovations in filtration and water care that keep your Highlife Collection spa water clean with as little work as possible.</p>\n<ol>\n<li><strong>FRESHWATER<sup>™</sup> SALT SYSTEM</strong><br />\nThis easy-to-use system eliminates the worry of keeping water clean, clear and sanitized for a full year. With just a little salt in your spa water, the system generates chlorine automatically and keeps water feeling soft without harsh chemical odor. This unique system makes spa ownership easier than ever by removing the guesswork and hassle of water care maintenance. <a href="/water-care/hot-spring-spas-water-care/hot-spring-spas-freshwater-salt-system/" style="color: yellow !important;">Learn More</a>.</li>\n<li><strong>INDUSTRY LEADING FILTRATION</strong><br />\nOnly Highlife Collection hot tubs offer 100% No Bypass Filtration, and up to 325 square feet of effective filtration area with exclusive, dishwasher-safe Tri-X<sup>®</sup> filters. The number of filters is matched to the power of the jet pumps to provide balanced filtration, allowing 100% of your spa water to pass through the filters 100% of the time – even when the jets are on, which is when other spas bypass the filters.</li>\n</ol>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (991, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (991, 'image-slider', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (991, '_image-slider', 'field_558d8be2f901f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (991, 'feature-video', '<p><img class="alignnone size-full wp-image-1012365" src="https://watkinsdealer.s3.amazonaws.com/Hot%20Tub%20Images/Hot%20Spring%20Spas/2019/features/highlife/highlife-water-feature.jpg" alt="" width="600" height="346" /></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (991, '_feature-video', 'field_558d8c12f9022');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (992, '_edit_lock', '1549481463:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (992, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (992, 'feature-name', 'Quality');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (992, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (992, 'feature-header', 'ABSOLUTE BEST HOT TUB OWNERSHIP EXPERIENCE<r></r>');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (992, '_feature-header', 'field_558d8b87f901c');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (992, 'feature-body', '<h4>THE ABSOLUTE BEST HOT TUB OWNERSHIP EXPERIENCE®</h4>\n<p>No matter which model you select, you can count on superior quality, comprehensive warranties and outstanding customer care from our experienced dealers.</p>\n<p><strong>COMMITTED TO OUR CUSTOMERS</strong></p>\n<p>Our dedication to high-quality construction and unparalleled customer care means you can enjoy your Hot Spring® spa for years to come. You can count on support from our network of experienced and professional retailers and our straightforward warranties to ensure your spa is always running at its best. We don’t expect you to take our word for it though. We are proud to share the real experiences of our customer’s right here on our website.</p>\n<p>Read <a class="fancybox" style="color: yellow !important;" href="http://www.hotspring.com/why-hot-spring-hot-tubs/product-reviews" target="_blank">reviews</a> from Hot Spring owners and learn about the Absolute Best Hot Tub Ownership Experience.</p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (992, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (992, 'image-slider', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (992, '_image-slider', 'field_558d8be2f901f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (992, 'feature-video', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (992, '_feature-video', 'field_558d8c12f9022');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (993, '_edit_lock', '1549419330:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (993, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (993, 'feature-name', 'Design');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (993, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (993, 'feature-header', 'REVOLUTIONARY NEW SPA DESIGN');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (993, '_feature-header', 'field_558d8b87f901c');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (993, 'feature-body', '<h4>INNOVATIVE DESIGN</h4>\n<p>The Highlife Collection is our top-tier luxury spa line offering unmatched visual appeal and innovative technology.</p>\n<ul>\n<li>Walnut and Driftwood cabinets feature a subtle grain pattern</li>\n<li>Brushed Nickel and Bronze finishes give a unique metallic effect</li>\n<li>Sandstone and Shale cabinets have stone-like texture</li>\n<li>Elegant, complementary shell colors selected by design experts</li>\n<li>Comfortable, sculpted seating and stylish details throughout</li>\n<li>Wireless, waterproof remote control for ease of use from any seat</li>\n<li>Customizable zone lighting to create the perfect ambiance inside or outside the spa</li>\n</ul>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (993, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (993, 'image-slider', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (993, '_image-slider', 'field_558d8be2f901f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (993, 'feature-video', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (993, '_feature-video', 'field_558d8c12f9022');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (993, 'feature-format', 'Image');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (993, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (993, 'feature-single-image', '1012352');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (993, '_feature-single-image', 'field_558dc33856974');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, 'feature-format', 'Image-Slider & Video');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (983, 'feature-format', 'Double Video');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (983, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (983, 'feature-single-image', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (983, '_feature-single-image', 'field_558dc33856974');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (992, 'feature-format', 'Double Video');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (992, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (992, 'feature-single-image', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (992, '_feature-single-image', 'field_558dc33856974');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (991, 'feature-format', 'Video');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (991, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (991, 'feature-single-image', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (991, '_feature-single-image', 'field_558dc33856974');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1600, '_edit_lock', '1445297972:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1600, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1600, 'feature-name', 'Plug-N-Play');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1600, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1600, 'feature-header', 'TEST HEADER');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1600, '_feature-header', 'field_558d8b87f901c');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1600, 'feature-body', '<h2 style="text-align: left;"><span style="color: #ffffff;">DO IT YOURSELF!</span></h2>\n<p><strong>Simply plug it in and enjoy!</strong><br />\nHate spending long hours assembling things? So do we. Save money and time with our Plug-N-Play technology which requires no additional wiring or expensive 230v installation. Simply fill up your hot tub, plug it into any standard 110v outlet, and enjoy!</p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1600, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1600, 'feature-format', 'Image');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1600, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1600, 'feature-single-image', '1018390');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1600, '_feature-single-image', 'field_558dc33856974');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1625, '_edit_lock', '1467054228:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1625, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1625, 'feature-name', 'Portable');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1625, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1625, 'feature-header', 'Test Header');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1625, '_feature-header', 'field_558d8b87f901c');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1625, 'feature-body', '<h2><span style="color: #ffffff;">PORTABLE HOT TUBS YOU&#8217;LL LOVE.</span></h2>\n<p><strong>Hot and ready whenever, wherever you are.</strong><br />\nFreeflow Spas has hot tubs that can fit your backyard, including condo balconies and porches. We even have a triangular portable hot tub for corner spaces! Refer to product specifications for weight.</p>\n<p>Don’t own your home? No worries! Our spas are perfect for renters too, because there’s no custom installation required. Our spas can be filled with a garden hose and plugged directly into any standard 110v outlet.</p>\n<p>Do you move a lot? Take your spa with you. Freeflow Spas’ lightweight unibody design means you can easily take it with you.</p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1625, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1625, 'feature-format', 'Image');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1625, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1625, 'feature-single-image', '1018389');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1625, '_feature-single-image', 'field_558dc33856974');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1626, '_edit_lock', '1579805961:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1626, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1626, 'feature-name', 'Energy');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1626, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1626, 'feature-header', 'Energy Efficiency');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1626, '_feature-header', 'field_558d8b87f901c');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1626, 'feature-body', '<h2 style="text-align: left;"><span style="color: #ffffff;">ENERGY EFFICIENT HOT TUBS.</span></h2>\n<p><strong>For low monthly operating costs.</strong><br />\nFreeflow Spas hot tubs are fully foamed for maximum energy efficiency. Paired with the thermal locking cover (that comes with your spa purchase), you can keep your warm water in so that it&#8217;s ready to use whenever you need a soak. Plus, our digital control panel puts the power in your hand to activate eco-friendly modes that only have your hot tub run when you need it to. No more water filter cycles or hot water escaping.</p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1626, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1626, 'feature-format', 'Image');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1626, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1626, 'feature-single-image', '1018388');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1626, '_feature-single-image', 'field_558dc33856974');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3078, '_edit_lock', '1455661684:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3078, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3078, 'feature-name', 'Energy');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3078, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3078, 'feature-body', '<h4>ENERGY EFFICIENCY</h4>\n<p>Highlife® NXT Collection spas offer our very best in efficiency and energy saving design – which is why we call these models <strong><em>Super Energy Efficient</em></strong>. This is just one of the ways a Highlife NXT Collection spa delivers the best value over time.</p>\n<p><strong>SAVING YOU MONEY</strong></p>\n<p>Highlife NXT Collection models feature our complete Energy Smart® system. Every aspect of the spa has been optimized to create heat efficiently and maximize heat retention.</p>\n<ul>\n<li>Totally insulated with multiple layers of foam to lock in heat</li>\n<li>SilentFlo® 5000 circulation pump that uses less energy than a 40 watt light bulb</li>\n<li>Custom-designed spa covers with an exclusive hinge seal to lock in heat</li>\n<li>Our No-Fault® heater that maximizes heat transfer and is covered by an unconditional 5-year warranty</li>\n<li>A pump shroud captures heat from the equipment compartment and transfers it to the water</li>\n<li>SmartJet® system lets you direct power only to the jet groups you want to use</li>\n</ul>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3078, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3078, 'feature-format', 'Video');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3078, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3078, 'feature-single-image', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3078, '_feature-single-image', 'field_558dc33856974');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3080, '_edit_lock', '1455661678:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3080, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3080, 'feature-name', 'Design');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3080, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3080, 'feature-body', '<h4>REVOLUTIONARY NEW SPA DESIGN</h4>\n<p>The Highlife® Collection NXT was designed with help from the experts at Designworks, a BMW Group Company. Using a blank canvas approach, Designworks provided concept ideation and design refinement support throughout the development process. Designworks&#8217; design proficiency, combined with the Hot Spring design team’s skill at leveraging innovative technology, culminated in a revolutionary new spa design.</p>\n<ul>\n<li>Everwood® HD spa cabinet provides the richness of real wood in contemporary colors</li>\n<li>Elegant, complementary shells colors selected by experts at Designworks</li>\n<li>Comfortable sculpted seating, stylish details and more useable space along the bartop</li>\n<li>Customizable zone lighting to create the perfect ambiance inside or outside the spa</li>\n<li>Easy to operate LCD control panel or wireless remote control with intuitive menus</li>\n</ul>\n<p><a href="/hot-tubs/hot-spring/highlife-nxt/#models">Browse models</a> to see available cabinet and shell colors.</p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3080, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3080, 'feature-format', 'Video');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3080, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3080, 'feature-single-image', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3080, '_feature-single-image', 'field_558dc33856974');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3080, 'image-slider', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3080, '_image-slider', 'field_558d8be2f901f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3186, '_edit_lock', '1519951148:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3186, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3186, 'feature-name', 'Massage');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3186, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3186, 'feature-body', '<h4 style="text-align: center;">POWERFUL JETS</h4>\n<p>Limelight<sup>®</sup> Collection spas are designed to feel as good as they look. Comfortable seats feature powerful jets that massage from your shoulders to your toes, providing targeted relief to help you feel your best.</p>\n<h4 style="text-align: center;">THE PERFECT MASSAGE</h4>\n<p>Limelight<sup>®</sup> Collection spas feature a variety of jets ranging from targeted Precision jets, to XL combination jets that soothe larger muscles.</p>\n<ul>\n<li>Combination XL jets provide a broad, robust massage to relieve tension in large areas, and can be adjusted to provide a direct stream or rotating massage</li>\n</ul>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3186, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3186, 'feature-format', 'Video');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3186, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3186, 'image-slider', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3186, '_image-slider', 'field_558d8be2f901f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3186, 'feature-video', '<p><img class="alignnone size-full wp-image-1018616" src="https://csp-hot-spring-spas.s3.amazonaws.com/content-blocks/features/images/massage-460x275.jpg" alt="" width="460" height="275" /></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3186, '_feature-video', 'field_558d8c12f9022');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3188, '_edit_lock', '1519950159:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3188, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3188, 'feature-name', 'Design');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3188, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3188, 'feature-body', '<h4 style="text-align: center;">THOUGHTFUL DESIGN</h4>\n<p>From the dramatic shell details to the brushed stainless-steel jet details and multiple points of light, your Limelight<sup>®</sup>Collection spa will surely turn heads. Make your personal retreat a stunning addition to your home or backyard.</p>\n<ul>\n<li>Beautiful, yet durable, Everwood<sup>®</sup> siding in three colors</li>\n<li>Uniquely sculpted shell interior</li>\n<li>Elegant shell colors ranging from pearlescent to marble-like</li>\n<li>Large, bold jets</li>\n<li>An intricate foot well pattern</li>\n<li>A sensor-driven logo light for at-a-glance diagnostics – you’ll know when your spa is at the set temperature and when maintenance or service is required</li>\n<li>Multiple points of colored lighting</li>\n</ul>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3188, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3188, 'feature-format', 'Double Video');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3188, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3188, 'feature-single-image', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3188, '_feature-single-image', 'field_558dc33856974');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3194, '_edit_lock', '1549578639:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3194, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3194, 'feature-name', 'Water');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3194, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3194, 'feature-body', '<h4>EASY WATER CARE</h4>\n<p>Limelight<sup>®</sup> Collection models offer easy-to-use water care systems that help you spend less time maintaining your spa and more time enjoying it.</p>\n<ol>\n<li><strong>FRESHWATER<sup>™</sup> SALT SYSTEM</strong><br />\nThis easy-to-use system eliminates the worry of keeping water clean, clear and sanitized for a full year. With just a little salt in your spa water, the system generates chlorine automatically and keeps water feeling soft without harsh chemical odor. This unique system makes spa ownership easier than ever by removing the guesswork and hassle of water care maintenance. <a href="/water-care/hot-spring-spas-water-care/hot-spring-spas-freshwater-salt-system/" style="color: yellow !important;">Learn More</a>.</li>\n<li><strong>FRESHWATER<sup>®</sup> OZONE SYSTEM</strong><br />\nKeep your water clean and clear, while reducing the need for chlorine. This system combines the cleaning power of the FreshWater<sup>®</sup> III high-output ozone generator with MPS non-chlorine oxidizer and silver ions for protection against contaminants. <a style="color: yellow !important;" href="/water-care/hot-spring-spas-water-care/hot-spring-spas-freshwater-ozone-system/">Learn More</a>.</li>\n</ol>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3194, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3194, 'feature-format', 'Double Video');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3194, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3194, 'feature-single-image', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3194, '_feature-single-image', 'field_558dc33856974');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3194, 'feature-video', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3194, '_feature-video', 'field_558d8c12f9022');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3214, '_edit_lock', '1519951878:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3214, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3214, 'feature-name', 'Energy');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3214, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3214, 'feature-body', '<h4 style="text-align: center;">ENERGY EFFICIENCY</h4>\n<p>All Hot Spring<sup>®</sup> spas offer Energy Smart<sup>®</sup> features, which help your spa deliver the best value over time.</p>\n<p><strong>LOCKS IN HEAT</strong></p>\n<p>Limelight<sup>®</sup> Collection spas feature FiberCor<sup>®</sup> insulation, which is provides 4 times denser than standard ½ lb. foam. Combined with other energy-efficient features, Limelight Collection spas lock in heat to reduce monthly energy costs. Limelight Collection spas offer the following Energy Smart<sup>®</sup>features:</p>\n<ul>\n<li>Custom-designed spa covers offer an exclusive hinge seal to lock in heat</li>\n<li>SmartJet<sup>®</sup> system lets you direct power only to the jet groups you want to use</li>\n</ul>\n<p><a href="/energy-efficient-hotspring/" style="color: yellow !important;">Estimate your monthly operating costs &gt;</a></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3214, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3214, 'feature-format', 'Double Video');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3214, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3214, 'feature-single-image', '1012351');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3214, '_feature-single-image', 'field_558dc33856974');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3215, '_edit_lock', '1519950380:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3215, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3215, 'feature-name', 'Quality');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3215, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3215, 'feature-body', '<h4 style="text-align: center;">THE ABSOLUTE BEST HOT TUB OWNERSHIP EXPERIENCE®</h4>\n<p>No matter which model you select, you can count on superior quality, comprehensive warranties and outstanding customer care from our experienced dealers.</p>\n<p><strong>COMMITTED TO OUR CUSTOMERS</strong></p>\n<p>Our dedication to high-quality construction and unparalleled customer care means you can enjoy your Hot Spring<sup>®</sup> spa for years to come. You can count on support from our network of experienced and professional retailers and our straightforward warranties to ensure your spa is always running at its best. We don’t expect you to take our word for it though. We are proud to share the real experiences of our customer’s right here on our website.</p>\n<p>Read what Hot Spring owners have to say. <a style="color:yellow !important;" href="http://www.hotspring.com/why-hot-spring-hot-tubs/product-reviews" target="_blank" rel="noopener">Visit Ratings and Reviews &gt;</a></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3215, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3215, 'feature-format', 'Video');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3215, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3215, 'feature-single-image', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3215, '_feature-single-image', 'field_558dc33856974');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3215, 'feature-video', '<p><img class="alignnone size-full wp-image-1018622" src="https://csp-hot-spring-spas.s3.amazonaws.com/content-blocks/features/images/quality-hot-tub-features.jpg" alt="" width="461" height="269" /></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3215, '_feature-video', 'field_558d8c12f9022');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3218, '_edit_lock', '1549418826:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3218, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3218, 'feature-name', 'Quality');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3218, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3218, 'feature-body', '<p>The Absolute Best Hot Tub Ownership Experience®</p>\n<p>Hot Spring spas are consistently recognized for outstanding quality and value. Dedication and experience add up to unsurpassed quality and reliability for you and your family. Make your spa part of your daily wellness routine, you can count on it to be hot and ready when you are, for years to come.</p>\n<p>For more that 40 years, we built our reputation on quality, but you don’t have to take our word for it. Read for yourself what our real Hot Spring Spas owners are saying about their experience. <span style="color: #ffff00;"><a style="color: #ffff00;" href="http://www.hotspring.com/why-hot-spring-hot-tubs/product-reviews">Read Reviews</a></span></p>\n<p>&nbsp;</p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3218, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3218, 'feature-format', 'Video');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3218, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3218, 'feature-single-image', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3218, '_feature-single-image', 'field_558dc33856974');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3218, 'feature-video', '<p><img src="https://watkinsdealer.s3-us-west-2.amazonaws.com/Hot+Tub+Images/Hot+Spring+Spas/2020/features/feature-hs-relay-quality.jpg" alt="Couple riding on bicylcles" width="100%"></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3218, '_feature-video', 'field_558d8c12f9022');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3219, '_edit_lock', '1549481611:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3219, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3219, 'feature-name', 'Massage');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3219, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3219, 'feature-body', '<p>Complete Hydrotherapy Experience</p>\n<p>Every aspect of your spa is precision engineered to deliver the ultimate massage experience. Ergonomically designed shells are shaped to fit the body’s contours and position you to make the most of our legendary Hot Spring hydromassage systems.</p>\n<p>You’ll emerge energized and inspired – ready to be your best.</p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3219, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3219, 'feature-format', 'Double Video');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3219, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3219, 'feature-single-image', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3219, '_feature-single-image', 'field_558dc33856974');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3220, '_edit_lock', '1549481610:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3220, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3220, 'feature-name', 'Energy');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3220, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3220, 'feature-body', '<p>Money-Saving Efficiency</p>\n<p>Use your spa every day with features that work together as part of the Energy Smart® system to keep energy costs down. FiberCor® insulation completely fills the spa cabinet with insulation that’s four times more dense than standard half-pound foam. Custom-designed, insulating spa covers provide a tight seal to lock in heat. And our patented No-Fault® heater maximizes heat transfer to the water. Your spa will be there for you, hot and ready with money-saving efficiency.</p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3220, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3220, 'feature-format', 'Video');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3220, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3220, 'feature-single-image', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3220, '_feature-single-image', 'field_558dc33856974');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3221, '_edit_lock', '1549419237:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3221, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3221, 'feature-name', 'Water');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3221, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3221, 'feature-body', '<p>Easy Water Care</p>\n<p>Hot Spot® Collection spas come ready for the FROG® @ease® in-line sanitizing system.* Pre-filled cartridges with SmartChlor® technology and minerals self-regulate to keep water crystal clear with less effort. @ease creates softer feeling water that’s virtually free of chemical odors since the system works with up to 75% less chlorine.*</p>\n<p>*Available in the U.S. only; bromine is available in Canada.</p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3221, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3221, 'feature-format', 'Double Video');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3221, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3221, 'feature-single-image', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3221, '_feature-single-image', 'field_558dc33856974');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3222, '_edit_lock', '1549417181:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3222, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3222, 'feature-name', 'Design');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3222, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3222, 'feature-body', '<p>Beautify Your Space</p>\n<p>Designed to delight the senses, each spa features eye-catching finishes, dramatic LED lighting, sleek metallic corners, and distinctive design details. Subtly embossed cabinets evoke the beauty of natural materials with the durability of advanced composites. Choose from a soothing color palate that follows current design trends and complements your indoor and outdoor space.</p>\n<p>A large bartop, contoured seating, and integrated pillows complement the overall design for a unique and on-trend look.</p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3222, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3222, 'feature-format', 'Video');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3222, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3222, 'feature-single-image', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3222, '_feature-single-image', 'field_558dc33856974');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3186, 'feature-single-image', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3186, '_feature-single-image', 'field_558dc33856974');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3219, 'feature-video', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3219, '_feature-video', 'field_558d8c12f9022');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3234, '_edit_lock', '1455661617:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3234, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3234, 'feature-name', 'Massage');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3234, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3234, 'feature-body', '<h4>THE PERFECT MASSAGE</h4>\n<p>Highlife® Collection NXT spas feature up to 8 different jets, offering different types of massage for various parts of the body:</p>\n<ul>\n<li>Every Highlife Collection NXT spa features the Moto-Massage® DX jet that provides two powerful streams of water that sweep up and down the length of your back – there is nothing else like it</li>\n<li>The Rotary Hydromassage jet performs like the fingers of a professional masseuse, with rotating nozzles that soothe your back, neck, calves and wrists</li>\n<li>Precision® jets work together in a powerful cluster to relieve tension in your back, neck and calves</li>\n<li>HydroStream® jets soothe tired muscles with constant streams of flowing water that relieve tension</li>\n<li>Directional Hydromassage jets provide targeted relief to problem areas with easy-to-adjust nozzles</li>\n<li>The four Quartet jets work in harmony to melt away tension in your neck and shoulders.</li>\n</ul>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3234, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3234, 'feature-format', 'Video');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3234, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3234, 'feature-single-image', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3234, '_feature-single-image', 'field_558dc33856974');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3234, 'image-slider', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3234, '_image-slider', 'field_558d8be2f901f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3234, 'feature-video', '<p><img class="alignnone size-full wp-image-1000103" src="https://csp-hot-spring-spas.s3.amazonaws.com/content-blocks/features/images/Massage_hL_1.jpg" alt="" width="461" height="275" /></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3234, '_feature-video', 'field_558d8c12f9022');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3372, '_edit_lock', '1476125987:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3372, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3372, 'feature-name', 'Water');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3372, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3372, 'feature-body', '<h4>CLEANER SPA WATER</h4>\n<p>Crystal clear spa water is essential to your soaking experience, which is why we have invested in innovations in filtration and water care that keep your Highlife® Collection NXT spa water clean with as little work as possible.</p>\n<ol>\n<li style="list-style-type: none;">\n<ol>\n<li style="list-style-type: none;">\n<ol>\n<li><strong>ACE<sup>®</sup> Salt Water Sanitizing System<br />\n</strong>The <a href="/product/spa-accessories/ace-salt-water-sanitizing-system/" target="_blank" rel="noopener">patented ACE system</a> uses a diamond electrode to automatically generate chlorine sanitizer and other powerful cleaners from salt and water. You’ll spend less time maintaining your spa water, and use fewer bottled products which helps your spa water last longer between changes. This Hot Spring exclusive is an option for all Highlife NXT Collection spa models.</li>\n<li>The EverFresh water care system is a popular water care system among Hot Spring owners. The powerful combination of the FreshWater® III CD ozone system, FreshWaterAg+ Silver Ion Cartridge and MPS non-chlorine shock keeps spa water sparkling clean with reduced levels of chlorine. The FreshWater III ozone system is an option for all Hot Spot spa models.</li>\n</ol>\n</li>\n</ol>\n</li>\n</ol>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3372, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3372, 'feature-format', 'Video');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3372, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3372, 'feature-single-image', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3372, '_feature-single-image', 'field_558dc33856974');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3222, 'slide_template', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3221, 'slide_template', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3220, 'slide_template', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (993, 'slide_template', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3234, 'slide_template', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, 'slide_template', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3372, 'slide_template', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3080, 'slide_template', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3078, 'slide_template', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (993, 'lazyload_thumbnail_quality', 'default');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (991, 'slide_template', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (991, 'lazyload_thumbnail_quality', 'default');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3372, 'lazyload_thumbnail_quality', 'default');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3234, 'lazyload_thumbnail_quality', 'default');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3078, 'lazyload_thumbnail_quality', 'default');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (992, 'slide_template', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (992, 'lazyload_thumbnail_quality', 'default');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (983, 'slide_template', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (983, 'lazyload_thumbnail_quality', 'default');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, 'lazyload_thumbnail_quality', 'default');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3080, 'lazyload_thumbnail_quality', 'default');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3215, 'slide_template', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3215, 'lazyload_thumbnail_quality', 'default');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3218, 'slide_template', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3218, 'lazyload_thumbnail_quality', 'default');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3219, 'slide_template', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3219, 'lazyload_thumbnail_quality', 'default');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3186, 'slide_template', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3188, 'slide_template', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3194, 'slide_template', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3214, 'slide_template', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3372, '_yoast_wpseo_content_score', '30');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3372, 'feature_video_1', '<iframe src="https://www.youtube.com/embed/LDUSknYRFAI?rel=0&amp;showinfo=0" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe>');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3372, '_feature_video_1', 'field_55f7324aacc53');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3372, 'feature_video_2', '<iframe src="https://www.youtube.com/embed/qQuUrS2PXRA?rel=0&amp;showinfo=0" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe>');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3372, '_feature_video_2', 'field_55f7325aacc54');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3372, '_yoast_wpseo_primary_feature-cat', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (991, '_yoast_wpseo_primary_feature-cat', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (991, '_yoast_wpseo_content_score', '30');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (991, 'feature_video_1', '<iframe src="https://www.youtube.com/embed/LDUSknYRFAI?rel=0&amp;showinfo=0" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe>');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (991, '_feature_video_1', 'field_55f7324aacc53');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (991, 'feature_video_2', '<iframe src="https://www.youtube.com/embed/qQuUrS2PXRA?rel=0&amp;showinfo=0" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe>');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (991, '_feature_video_2', 'field_55f7325aacc54');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1005821, '_edit_lock', '1467055793:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1005821, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1005821, 'feature-name', 'WATER');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1005821, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1005821, 'feature-body', '<h4>CLEANER SPA WATER</h4>\r\n<ol>\r\n 	<li><strong>Everfresh® System with Plasma Ozone</strong>Our exclusive EverFresh® System is a more natural approach to water care that’s optional on every Hot Spring Highlife and NXT Spa we sell. The beauty of EverFresh is that it’s virtually chlorine free! Never again soak in water with overpowering odor, or harsh drying effects on your skin. EverFresh will make routine water care easier, and keep your spa water crystal clean for longer periods of time.<strong>EverFresh consists of two main components that work in harmony with your Hot Spring’s 100% filtration:</strong>\r\n<ol>\r\n 	<li><strong>The High Output Ozone System</strong> continuously injects millions of tiny, highly concentrated ozone bubbles in the water, neutralizing contaminants on contact. Unlike ozone systems that use a UV bulb that need to be replaced on a regular basis (at considerable expense); our system uses a plasma chip that requires virtually no maintenance.</li>\r\n</ol>\r\n<ol start="2">\r\n 	<li><strong>The FreshWater AG+ Silver Ion Cartridge</strong>. Combined with the plasma chip ozonator, the silver ion cartridge is installed in one of the spas’ filters. Silver ions are then continuously introduced into the spa water. You’ll add a pre-measured “pod” of <a href="https://www.olympichottubestore.com/category-s/1910.htm">SilkBalance Shock Gems</a> after each use, which “activates” the silver ions to inhibit the growth of bacteria, refreshing and brightening the water. Simply replace the cartridge every four months for on-going protection. Signing up for our<a href="https://www.olympichottubestore.com/hot-tub-cleaning-service-buy-online-on-sale-s/1836.htm"> EverCare™</a> Program makes this a breeze.</li>\r\n</ol>\r\n</li>\r\n 	<li><strong>Silk Balance makes hot tub water feel like silk</strong>. Your skin will feel soft and young again after every soak. If you’ve tried other hot tubs, you’ll notice the difference immediately: It’s perfect for sensitive skin. There’s no smell; no feeling of sitting in a vat of chemicals that can dry out your skin. You have to feel it to believe it!<strong>You’ll smell only fresh, pure water.</strong><strong>You’ll enjoy the best water quality day after day.</strong>Our hot tub water is…simply better. We’ve made hot tub water care simple and easy. Adding Silk Balance once a week keeps spa water in perfect harmony — it looks better, smells better and feels better, creating the bathing experience you want for yourself and your family.<strong>Makes hot tub water care simple!</strong></li>\r\n</ol>\r\n&nbsp;\r\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1005821, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1005821, 'feature-format', 'Video');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1005821, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1005821, 'feature-video', '<iframe src="https://www.youtube.com/embed/qQuUrS2PXRA?rel=0&amp;showinfo=0" width="560" height="315" frameborder="0" allowfullscreen="allowfullscreen"></iframe>');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1005821, '_feature-video', 'field_558d8c12f9022');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1005821, '_yoast_wpseo_primary_feature-cat', '123');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1005821, '_yoast_wpseo_content_score', '30');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3194, '_yoast_wpseo_primary_feature-cat', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3194, '_yoast_wpseo_content_score', '30');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (992, '_yoast_wpseo_primary_feature-cat', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (992, '_yoast_wpseo_content_score', '30');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3188, '_yoast_wpseo_primary_feature-cat', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3188, '_yoast_wpseo_content_score', '30');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3215, '_yoast_wpseo_primary_feature-cat', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3215, '_yoast_wpseo_content_score', '30');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3186, '_yoast_wpseo_primary_feature-cat', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3186, '_yoast_wpseo_content_score', '30');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3214, 'feature_video_1', '<p><img class="alignleft size-full wp-image-1018621" src="https://csp-hot-spring-spas.s3.amazonaws.com/content-blocks/features/images/limelight-features-energy_0.jpg" alt="" width="461" height="275" /></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3214, '_feature_video_1', 'field_55f7324aacc53');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3214, 'feature_video_2', '<p><a href="/energy-efficient-hotspring/"><img class="size-full wp-image-1018509 alignleft" src="https://csp-hot-spring-spas.s3.amazonaws.com/content-blocks/features/images/EnergyEfficient_2.jpg" alt="" width="461" height="275" /></a></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3214, '_feature_video_2', 'field_55f7325aacc54');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3214, '_yoast_wpseo_primary_feature-cat', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3214, '_yoast_wpseo_content_score', '30');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (993, '_yoast_wpseo_primary_feature-cat', '330');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (993, '_yoast_wpseo_content_score', '30');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3221, '_yoast_wpseo_primary_feature-cat', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3221, '_yoast_wpseo_content_score', '30');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3221, 'feature-video', '<p><img class="alignnone size-full wp-image-3228" src="https://csp-hot-spring-spas.s3.amazonaws.com/content-blocks/features/images/MPD-HotSpotWater1.jpg" alt="Hot Spot Water Care" width="461" height="275" /></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3221, '_feature-video', 'field_558d8c12f9022');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3222, 'image-slider', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3222, '_image-slider', 'field_558d8be2f901f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3222, 'feature-video', '<p><img class="alignnone size-full wp-image-3233" src="https://watkinsdealer.s3-us-west-2.amazonaws.com/Hot+Tub+Images/Hot+Spring+Spas/2020/features/Hot-Spring-Relay-Design-feature-2020.jpg" alt="Hot Spot Spa Design" width="461" height="275" /></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3222, '_feature-video', 'field_558d8c12f9022');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3222, '_yoast_wpseo_primary_feature-cat', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3222, '_yoast_wpseo_content_score', '30');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3220, 'feature-video', '<p><img src="https://watkinsdealer.s3-us-west-2.amazonaws.com/Hot+Tub+Images/Hot+Spring+Spas/2020/features/feature-hs-relay-energy.jpg" alt="Tempo Spa Cover" width="461" height="275" class="alignnone size-full wp-image-3232" /></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3220, '_feature-video', 'field_558d8c12f9022');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3220, '_yoast_wpseo_primary_feature-cat', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3220, '_yoast_wpseo_content_score', '30');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3221, 'feature_video_1', '<p><img class="alignnone size-full wp-image-3228" src="https://watkinsdealer.s3-us-west-2.amazonaws.com/Hot+Tub+Images/Hot+Spring+Spas/2020/features/feature-hs-relay-water.jpg" alt="Hot Spot Water Care" width="461" height="275" /></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3221, '_feature_video_1', 'field_55f7324aacc53');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3221, 'feature_video_2', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3221, '_feature_video_2', 'field_55f7325aacc54');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3219, 'feature_video_1', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3219, '_feature_video_1', 'field_55f7324aacc53');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3219, 'feature_video_2', '<p><img class="alignnone size-full wp-image-3227" src="https://watkinsdealer.s3-us-west-2.amazonaws.com/Hot+Tub+Images/Hot+Spring+Spas/2020/features/feature-hs-relay-massage.jpg" alt="Hot Spot SX massage" width="600" height="224" /></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3219, '_feature_video_2', 'field_55f7325aacc54');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3219, '_yoast_wpseo_primary_feature-cat', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3219, '_yoast_wpseo_content_score', '30');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (983, '_yoast_wpseo_primary_feature-cat', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (983, '_yoast_wpseo_content_score', '30');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, '_yoast_wpseo_primary_feature-cat', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, '_yoast_wpseo_content_score', '30');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007669, '_edit_lock', '1549486367:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007669, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007669, 'feature-name', 'Design');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007669, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007669, 'feature-body', '<h4>INNOVATIVE DESIGN</h4>\r\nThe Highlife Collection is our top-tier luxury spa line offering unmatched visual appeal and innovative technology.\r\n<ul>\r\n 	<li>Walnut and Driftwood cabinets feature a subtle grain pattern</li>\r\n 	<li>Brushed Nickel and Bronze finishes give a unique metallic effect</li>\r\n 	<li>Sandstone and Shale cabinets have stone-like texture</li>\r\n 	<li>Elegant, complementary shell colors selected by design experts</li>\r\n 	<li>Comfortable, sculpted seating and stylish details throughout</li>\r\n 	<li>Wireless, waterproof remote control for ease of use from any seat</li>\r\n 	<li>Customizable zone lighting to create the perfect ambiance inside or outside the spa</li>\r\n</ul>');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007669, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007669, 'feature-format', 'Image');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007669, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007669, 'image-slider_0_image', '1007670');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007669, '_image-slider_0_image', 'field_558d8beff9020');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007669, 'image-slider_1_image', '1007671');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007669, '_image-slider_1_image', 'field_558d8beff9020');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007669, 'image-slider_2_image', '1007675');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007669, '_image-slider_2_image', 'field_558d8beff9020');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007669, 'image-slider_3_image', '1007674');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007669, '_image-slider_3_image', 'field_558d8beff9020');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007669, 'image-slider_4_image', '1007673');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007669, '_image-slider_4_image', 'field_558d8beff9020');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007669, 'image-slider', '5');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007669, '_image-slider', 'field_558d8be2f901f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007669, '_yoast_wpseo_primary_feature-cat', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007669, '_yoast_wpseo_content_score', '30');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007676, '_edit_lock', '1549419833:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007676, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007676, 'feature-name', 'Quality');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007676, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007676, 'feature-body', '<h4>ABSOLUTE BEST HOT TUB OWNERSHIP EXPERIENCE®</h4>\r\nNo matter which model you select, you can count on superior quality, comprehensive warranties and outstanding customer care from our experienced dealers.\r\n\r\n<strong>COMMITTED TO OUR CUSTOMERS</strong>\r\n\r\nOur dedication to high-quality construction and unparalleled customer care means you can enjoy your Hot Spring® spa for years to come. You can count on support from our network of experienced and professional retailers and our straightforward warranties to ensure your spa is always running at its best. We don’t expect you to take our word for it though. We are proud to share the real experiences of our customer’s right here on our website.\r\n\r\nRead <a class="fancybox" href="http://www.hotspring.com/why-hot-spring-hot-tubs/product-reviews" target="_blank">reviews</a> from Hot Spring owners and learn about the Absolute Best Hot Tub Ownership Experience.');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007676, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007676, 'feature-format', 'Double Video');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007676, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007676, 'feature_video_1', '<iframe src="https://www.youtube.com/embed/hD3DSTJFkJo" width="100%" height="300" frameborder="0" allowfullscreen="allowfullscreen"></iframe>');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007676, '_feature_video_1', 'field_55f7324aacc53');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007676, 'feature_video_2', '<img src="https://watkinsdealer.s3.amazonaws.com/Hot%20Tub%20Images/Hot%20Spring%20Spas/2019/features/highlife/highlife-quality.jpg" alt="Quality" width="461" height="275" class="alignnone size-full wp-image-1018528" />');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007676, '_feature_video_2', 'field_55f7325aacc54');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007676, '_yoast_wpseo_primary_feature-cat', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007676, '_yoast_wpseo_content_score', '30');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007677, '_edit_lock', '1557782614:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007677, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007677, 'feature-name', 'Water');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007677, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007677, 'feature-body', '<h4>CLEANER SPA WATER</h4>\r\nCrystal clear spa water is essential to your soaking experience, which is why we have invested in innovations in filtration and water care that keep your Highlife Collection spa water clean with as little work as possible.\r\n<ol>\r\n 	<li><strong>FRESHWATER<sup>™</sup> SALT SYSTEM</strong>\r\nThis easy-to-use system eliminates the worry of keeping water clean, clear and sanitized for a full year. With just a little salt in your spa water, the system generates chlorine automatically and keeps water feeling soft without harsh chemical odor. This unique system makes spa ownership easier than ever by removing the guesswork and hassle of water care maintenance. <a href="/water-care/freshwater-salt-system/">Learn More</a>.</li>\r\n 	<li><strong>INDUSTRY LEADING FILTRATION</strong>\r\nOnly Highlife Collection hot tubs offer 100% No Bypass Filtration, and up to 325 square feet of effective filtration area with exclusive, dishwasher-safe Tri-X<sup>®</sup> filters. The number of filters is matched to the power of the jet pumps to provide balanced filtration, allowing 100% of your spa water to pass through the filters 100% of the time – even when the jets are on, which is when other spas bypass the filters.</li>\r\n</ol>');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007677, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007677, 'feature-format', 'Video');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007677, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007677, 'feature-video', '<img class="alignnone size-full wp-image-1012365" src="https://watkinsdealer.s3.amazonaws.com/Hot%20Tub%20Images/Hot%20Spring%20Spas/2019/features/highlife/highlife-water-feature.jpg" alt="" width="600" height="346" />');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007677, '_feature-video', 'field_558d8c12f9022');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007677, '_yoast_wpseo_primary_feature-cat', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007677, '_yoast_wpseo_content_score', '30');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007678, '_edit_lock', '1549419899:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007678, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007678, 'feature-name', 'Energy');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007678, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007678, 'feature-body', '<h4>ENERGY EFFICIENCY</h4>\r\nHighlife® Collection spas offer our very best in efficiency and energy saving design – which is why we call these models <em>Super Energy Efficient</em>. This is just one of the ways a Highlife Collection spa delivers the best value over time.\r\n\r\n<strong>SAVING YOU MONEY</strong>\r\n\r\nHighlife Collection models feature our complete Energy Smart® system. Every aspect of the spa has been optimized to create heat efficiently and maximize heat retention.\r\n<ul>\r\n 	<li>Totally insulated with multiple layers of foam to lock in heat</li>\r\n 	<li>SilentFlo 5000® circulation pump that uses less energy than a 40 watt light bulb</li>\r\n 	<li>Custom-designed spa covers with an exclusive hinge seal to lock in heat</li>\r\n 	<li>Our No-Fault® heater that maximizes heat transfer and is covered by an unconditional 5-year warranty</li>\r\n 	<li>A pump shroud captures heat from the equipment compartment and transfers it to the water</li>\r\n 	<li>SmartJet® system lets you direct power only to the jet groups you want to use</li>\r\n</ul>');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007678, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007678, 'feature-format', 'Double Video');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007678, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007678, 'feature_video_1', '<img class="alignnone size-full wp-image-3310" src="https://watkinsdealer.s3.amazonaws.com/Hot%20Tub%20Images/Hot%20Spring%20Spas/2019/features/highlife/highlife-energy.jpg" alt="Vanguard Spa Cover" width="461" height="275" />');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007678, '_feature_video_1', 'field_55f7324aacc53');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007678, 'feature_video_2', '<a href="/energy-efficient-hotspring/"><img class="size-full wp-image-1018509 alignleft" src="https://csp-hot-spring-spas.s3.amazonaws.com/content-blocks/features/images/EnergyEfficient_2.jpg" alt="" width="461" height="275" /></a>');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007678, '_feature_video_2', 'field_55f7325aacc54');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007678, '_yoast_wpseo_primary_feature-cat', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007678, '_yoast_wpseo_content_score', '30');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007679, '_edit_lock', '1579743736:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007679, '_edit_last', '2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007679, 'feature-name', 'Massage');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007679, '_feature-name', 'field_558d8b74f901b');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007679, 'feature-body', '<h4>OUR JET PHILOSOPHY</h4>\r\nWe design spas based on how you will actually use them. The ComfortControl® system lets you customize the strength of massage. The SmartJet® system allows you to direct power to the jets you are using, instead of powering all the jets at once.\r\n\r\n<strong>THE PERFECT MASSAGE</strong>\r\n\r\nHighlife® Collection spas feature up to 7 different jets, offering different types of massage for various parts of the body:\r\n<ul>\r\n 	<li>Every Highlife Collection spa features the Moto-Massage® DX jet that provides two powerful streams of water that sweep up and down the length of your back – there is nothing else like it</li>\r\n 	<li>Precision® jets work together in a powerful cluster to relieve tension in your back, neck and calves</li>\r\n 	<li>Directional Hydromassage jets provide targeted relief to problem areas with easy-to-adjust nozzles</li>\r\n</ul>');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007679, '_feature-body', 'field_558d8baaf901d');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007679, 'feature-format', 'Image-Slider & Video');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007679, '_feature-format', 'field_558dc2765696f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007679, 'image-slider_0_image', '1007681');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007679, '_image-slider_0_image', 'field_558d8beff9020');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007679, 'image-slider_1_image', '1007680');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007679, '_image-slider_1_image', 'field_558d8beff9020');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007679, 'image-slider_2_image', '1007684');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007679, '_image-slider_2_image', 'field_558d8beff9020');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007679, 'image-slider', '3');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007679, '_image-slider', 'field_558d8be2f901f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007679, '_yoast_wpseo_primary_feature-cat', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007679, '_yoast_wpseo_content_score', '30');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007669, 'feature-single-image', '1007672');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007669, '_feature-single-image', 'field_558dc33856974');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007679, 'feature-video', '<iframe src="https://www.youtube.com/embed/DihcVsLEKyc" width="100%" height="300" frameborder="0" allowfullscreen="allowfullscreen"></iframe>');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1007679, '_feature-video', 'field_558d8c12f9022');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3194, 'feature_video_1', '<p><img class="alignleft size-full wp-image-1012365" src="https://s3-us-west-2.amazonaws.com/watkinsdealer/Hot-Tub-Accessories/freshwater+salt+sysltem+461x275.jpg" alt="" width="600" height="346" /></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3194, '_feature_video_1', 'field_55f7324aacc53');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3194, 'feature_video_2', '<p><img class="wp-image-1020691 size-full alignleft" src="https://s3.amazonaws.com/wp-agilitysquared/myproductdata/wp-content/uploads/2015/10/ozone-461x275.jpg" alt="" width="461" height="275" /></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3194, '_feature_video_2', 'field_55f7325aacc54');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3372, 'feature-video', '<p><img class="alignnone size-full wp-image-1012365" src="https://s3-us-west-2.amazonaws.com/watkinsdealer/Hot-Tub-Accessories/freshwater+salt+sysltem+461x275.jpg" alt="" width="600" height="346" /></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3372, '_feature-video', 'field_558d8c12f9022');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3222, 'image_slider_cdn', '3');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3222, '_image_slider_cdn', 'field_5c3fdbd6bfcba');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3214, 'image-slider', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3214, '_image-slider', 'field_558d8be2f901f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3214, 'feature-video', '<p><img class="size-full wp-image-3226 alignleft" src="http://mpd.designstudio.host/wp-content/uploads/2015/10/Hot-Spring-Flair-Energy.jpg" alt="Silent Flo Circulation" width="461" height="275" /></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3214, '_feature-video', 'field_558d8c12f9022');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3188, 'feature_video_1', '<p><img class="alignnone size-full wp-image-1018618" src="https://csp-hot-spring-spas.s3.amazonaws.com/content-blocks/features/images/limelight-features-design-1-461x275.jpg" alt="" width="461" height="275" /></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3188, '_feature_video_1', 'field_55f7324aacc53');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3188, 'feature_video_2', '<p><img class="alignnone size-full wp-image-1018619" src="https://csp-hot-spring-spas.s3.amazonaws.com/content-blocks/features/images/limelight-features-design-2-461x275.jpg" alt="" width="461" height="275" /></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3188, '_feature_video_2', 'field_55f7325aacc54');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3080, 'feature-video', '<p><img class="alignnone size-full wp-image-3082" src="https://csp-hot-spring-spas.s3.amazonaws.com/content-blocks/features/images/features-highlife-nxt-design.png" alt="" width="461" height="275" /></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3080, '_feature-video', 'field_558d8c12f9022');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3078, 'feature-video', '<p><img class="alignnone size-full wp-image-3079" src="https://csp-hot-spring-spas.s3.amazonaws.com/content-blocks/features/images/features-highlife-nxt-energy.png" alt="" width="461" height="275" /></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3078, '_feature-video', 'field_558d8c12f9022');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (993, 'image_slider_cdn', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (993, '_image_slider_cdn', 'field_5c3fdbd6bfcba');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (992, 'feature_video_1', '<p><iframe src="https://www.youtube.com/embed/hD3DSTJFkJo" width="100%" height="300" frameborder="0" allowfullscreen="allowfullscreen"></iframe></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (992, '_feature_video_1', 'field_55f7324aacc53');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (992, 'feature_video_2', '<p><img src="https://watkinsdealer.s3.amazonaws.com/Hot%20Tub%20Images/Hot%20Spring%20Spas/2019/features/highlife/highlife-quality.jpg" alt="Quality" width="461" height="275" class="alignnone size-full wp-image-1018528" /></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (992, '_feature_video_2', 'field_55f7325aacc54');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (983, 'feature_video_1', '<p><img class="alignnone size-full wp-image-3310" src="https://watkinsdealer.s3.amazonaws.com/Hot%20Tub%20Images/Hot%20Spring%20Spas/2019/features/highlife/highlife-energy.jpg" alt="Vanguard Spa Cover" width="461" height="275" /></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (983, '_feature_video_1', 'field_55f7324aacc53');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (983, 'feature_video_2', '<p><a href="/energy-efficient-hotspring/"><img class="size-full wp-image-1018509 alignleft" src="https://csp-hot-spring-spas.s3.amazonaws.com/content-blocks/features/images/EnergyEfficient_2.jpg" alt="" width="461" height="275" /></a></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (983, '_feature_video_2', 'field_55f7325aacc54');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, 'image_slider_cdn', '3');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, '_image_slider_cdn', 'field_5c3fdbd6bfcba');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3222, 'image_slider_cdn_0_image_url', 'https://csp-hot-spring-spas.s3.amazonaws.com/content-blocks/features/images/MPD-Hot-Spot-Design.jpg');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3222, '_image_slider_cdn_0_image_url', 'field_5c3fdbfdbfcbb');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3222, 'image_slider_cdn_1_image_url', 'https://csp-hot-spring-spas.s3.amazonaws.com/content-blocks/features/images/distinctive-style-design-2.jpg');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3222, '_image_slider_cdn_1_image_url', 'field_5c3fdbfdbfcbb');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3222, 'image_slider_cdn_2_image_url', 'https://csp-hot-spring-spas.s3.amazonaws.com/content-blocks/features/images/distinctive-style-design3.jpg');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3222, '_image_slider_cdn_2_image_url', 'field_5c3fdbfdbfcbb');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, 'image_slider_cdn_0_image_url', 'https://watkinsdealer.s3.amazonaws.com/Hot+Tub+Images/Hot+Spring+Spas/2019/features/highlife/Highlife-Moto-Massage.jpg');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, '_image_slider_cdn_0_image_url', 'field_5c3fdbfdbfcbb');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, 'image_slider_cdn_1_image_url', 'https://watkinsdealer.s3.amazonaws.com/Hot+Tub+Images/Hot+Spring+Spas/2019/features/highlife/HLFeatures_JetsUpdate_03-1.jpg');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, '_image_slider_cdn_1_image_url', 'field_5c3fdbfdbfcbb');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, 'image_slider_cdn_2_image_url', 'https://watkinsdealer.s3.amazonaws.com/Hot+Tub+Images/Hot+Spring+Spas/2019/features/highlife/HLFeatures_JetsUpdate_01-1.jpg');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (982, '_image_slider_cdn_2_image_url', 'field_5c3fdbfdbfcbb');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1626, 'feature-video', '<p><img loading="lazy" class="alignnone size-full wp-image-3383" src="https://csp-freeflow-spas.s3.amazonaws.com/content-blocks/features/images/FFEnergyFEAT.png" alt="Energy efficient Freeflow" width="600" height="400" /></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1626, '_feature-video', 'field_558d8c12f9022');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1625, 'feature-video', '<p><img loading="lazy" src="https://csp-freeflow-spas.s3.amazonaws.com/content-blocks/features/images/FFPortableFEAT.png" alt="Freeflow portability" width="600" height="400" class="alignnone size-full wp-image-3384" /></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1625, '_feature-video', 'field_558d8c12f9022');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1600, 'feature-video', '<p><img loading="lazy" src="https://csp-freeflow-spas.s3.amazonaws.com/content-blocks/features/images/FFPlugFEAT.jpg" alt="Freeflow plugs in" width="600" height="401" class="alignnone size-full wp-image-3385" /></p>\n');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1600, '_feature-video', 'field_558d8c12f9022');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1626, '_yoast_wpseo_primary_feature-cat', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3218, 'image-slider', '');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3218, '_image-slider', 'field_558d8be2f901f');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3218, 'image_slider_cdn_0_image_url', 'https://watkinsdealer.s3.us-west-2.amazonaws.com/Hot%20Tub%20Images/Hot%20Spring%20Spas/2020/features/hot-spring-hot-spot-powerful-jets.webp');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3218, '_image_slider_cdn_0_image_url', 'field_5c3fdbfdbfcbb');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3218, 'image_slider_cdn', '1');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3218, '_image_slider_cdn', 'field_5c3fdbd6bfcba');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1013268, '_edit_lock', '1620252342:9');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1013915, '_edit_lock', '1661378661:9');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1013709, '_edit_lock', '1608061912:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1014214, '_edit_lock', '1608062121:2');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1013856, '_edit_lock', '1613772057:9');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1013379, '_edit_lock', '1664219414:9');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1013045, '_edit_lock', '1628091696:123');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1014103, '_edit_lock', '1662999614:9');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1013929, '_edit_lock', '1620225398:9');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1013268, '_edit_last', '9');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1013268, '_expiration-date-status', 'saved');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1013052, '_edit_lock', '1623879056:9');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1024410, '_edit_lock', '1691374629:1005');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1024410, '_edit_last', '9');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1024411, '_expiration-date-status', 'saved');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1024412, '_expiration-date-status', 'saved');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1024410, '_expiration-date-status', 'saved');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1013568, '_edit_lock', '1623879693:9');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1014235, '_edit_lock', '1623879727:9');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1013040, '_edit_lock', '1628091660:123');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1013042, '_edit_lock', '1628091668:123');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1013718, '_edit_lock', '1628091730:123');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1013250, '_edit_lock', '1657836881:9');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1013915, '_edit_last', '9');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1042595, '_tve_js_modules_gutenberg', 'a:0:{}');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1014032, '_edit_lock', '1676883737:9');
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1013255, '_edit_lock', '1691412722:1005');
